Repository salvo-rs/salvo, pull requests merged in 2025-05, with the labels that each got.

#1126 Enhanced support for anyhow::Error, (fixed anyhow fmt)
  crates/core/src/http/errors/status_error.rs
  crates/oapi/Cargo.toml
  crates/oapi/src/endpoint.rs
Labels: Review effort 2/5

#1134 Fix: impl Scribe for anyhow::Error{}
  crates/core/src/error.rs
Labels: Review effort 1/5

#1135 Add content-range support for static_embed
  crates/serve-static/src/embed.rs
Labels: Review effort 3/5

#1144 Do not log H3_NO_ERROR
  crates/core/src/conn/quinn/builder.rs
Labels: Review effort 1/5
